workflow update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -76,18 +76,18 @@ jobs:
         id: run_pentest
         run: ./scripts/pentest.sh
 
+      - name: Vulnerability found
+        if: steps.run_pentest.outputs.VULNERABILITY_FOUND == 'true'
+        run: |
+          echo -e "\033[0;31m\033[1mVulnerability detected. Failing the workflow.\033[0m"
+          exit 1
+
       - name: Upload Vulnerability Report
         run: ./scripts/report.sh
-        continue-on-error: true
 
       - uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: results.sarif
-
-      - if: steps.run_pentest.outputs.VULNERABILITY_FOUND == 'true'
-        run: |
-          echo -e "\033[0;31m\033[1mVulnerability detected. Failing the workflow.\033[0m"
-          exit 1
   
   deploy-production:
     needs: [pentest-staging]
